# src/models/synapse.py
import numpy as np

class Synapse:
    """
    Represents a plastic connection (Synapse) implementing Gated STDP.
    Plasticity is controlled by two competing neuromodulators (Dopamine and Adrenaline).
    """
    def __init__(self, initial_weight=0.1, tau_stdp=20.0, eta=0.02, 
                 dopa_gate_thresh=0.4, adre_gate_thresh=0.4):
        
        self.weight = initial_weight 
        self.tau_stdp = tau_stdp     
        self.eta = eta               
        
        self.dopa_gate_thresh = dopa_gate_thresh
        self.adre_gate_thresh = adre_gate_thresh # NEW: Adrenaline threshold
        
        self.pre_trace = 0.0         
        self.post_trace = 0.0

    def get_output_current(self, pre_spiked):
        """
        Calculates the synaptic current generated by the pre-neuron spike.
        I_syn = w * V_input_spike. (We assume V_input_spike = 5.0 nA when spiked).
        """
        if pre_spiked:
            return self.weight * 5.0 
        return 0.0
        
    def update_traces(self, pre_spiked, post_spiked, dt, dopamine_level, adrenaline_level):
        """
        Updates traces and applies two-factor GATED STDP: 
        Dopamine enables LTP; Adrenaline enables LTD.
        """
        
        # 1. Decay and Boost Traces (Critical for timing)
        self.pre_trace *= np.exp(-dt / self.tau_stdp)
        self.post_trace *= np.exp(-dt / self.tau_stdp)

        if pre_spiked:
            self.pre_trace += 1.0 
        if post_spiked:
            self.post_trace += 1.0 

        # 2. Check Gates
        is_dopa_learning = (dopamine_level >= self.dopa_gate_thresh)
        is_adre_unlearning = (adrenaline_level >= self.adre_gate_thresh) # NEW GATE

        # 3. Apply STDP (Learning Logic)
        
        # --- POTENTIATION (LTP: Strengthening) ---
        # Occurs ONLY if Dopamine is high AND Pre-before-Post condition met
        if is_dopa_learning:
            if pre_spiked and self.post_trace > 0: # Checks for coincidence
                self.weight += self.eta * self.post_trace * 5.0 # LTP
        
        # --- DEPRESSION (LTD: Weakening) ---
        # Occurs ONLY if Adrenaline is high AND Post-before-Pre condition met
        elif is_adre_unlearning:
             if post_spiked and self.pre_trace > 0: # Checks for coincidence
                self.weight -= self.eta * self.pre_trace * 1.0 # LTD

        # 4. Clip weights
        self.weight = np.clip(self.weight, 0.0, 1.0)